MANIFEST.in
README.md
requirements-inst.txt
requirements-test.txt
requirements.txt
scripts/bootstrap.py
setup.py
tests/integration/test_jaeger_client.py
tox.ini

Currently the requirements file and bootstrap process present users with an all or nothing dependency installation choice and the expectation that they've cloned the project repo.  These changes add an `sfx-py-trace-bootstrap` entry point for automatic instrumentor and tracer installation.  Also included are the option of instrumentor installations as package extras w/ a split instrumentor requirements file as the source of truth.

Expand setup bootstrap functionality

---

README.md
scripts/README.md
scripts/bootstrap.py
tests/integration/test_jaeger_client.py
tox.ini

Adds an additional uninstallation step to the bootstrap utility to ensure that the desired version of instrumentations and Jaeger are installed.  Also includes updated docs and some test coverage via installing undesired tracer and instrumentation versions before running bootstrap and integration tests for Django, Flask, and Jaeger.

Ensure sfx-py-trace-bootstrap installs desired libraries

---

README.md
noxfile.py
requirements-inst.txt
scripts/README.md
scripts/bootstrap.py
scripts/sfx_py_trace.py
scripts/site_/__init__.py
scripts/site_/sitecustomize.py
signalfx_tracing/libraries/django_/README.md
tests/integration/lib/runner_target_script.py
tests/integration/sitecustomize.py
tests/integration/test_runner.py

Updates the provided jaeger to be one without the Tornado dependency: https://github.com/signalfx/jaeger-client-python/tree/ot_20_http_sender_no_tornado.  This allows creation of a tracer in imported modules because all thread creation is deferred until actual tracing activity.
Also provides updates to sfx-py-trace to utilize the `site` library and improve the user experience for Django apps.

Source Jaeger without tornado and adopt in sfx-py-trace

---

README.md
noxfile.py
scripts/README.md
scripts/bootstrap.py

For supporting custom site packages targets or when building a Lambda function environment, it can be helpful to specify the target destination for instrumentations and dependencies.  These changes introduce a `-t` argument to `sfx-py-trace-bootstrap` and the bootstrap script to pass to the underlying pip command.
Also pork barreling package extras installation path to only work w/ cloned repositories and PyPI blocks this in newer pip versions.

Add target path for sfx-py-trace-bootstrap

---

README.md
scripts/README.md
scripts/sfx_py_trace.py
signalfx_tracing/instrumentation.py
signalfx_tracing/utils.py
tests/integration/test_runner.py
tests/unit/test_instrument.py
tests/unit/test_utils.py

For cases where users don't want to initiate instrumentation without having to modify their code or run configuration, these changes introduce `SIGNALFX_TRACING_ENABLED` as a bypass mechanism.

Provide instrumentation env var

---

README.md
scripts/README.md
signalfx_tracing/libraries/django_/README.md
signalfx_tracing/utils.py
tests/integration/test_jaeger_client.py

These changes added some ~memoization to `create_tracer` such that a jaeger singleton will always be returned on multiple calls.  Also update the endpoint environment variable target to localhost and its name (bw-compat for the time being).

Ensure create_tracer returns single instance and update url envvar

---

noxfile.py
setup.py
signalfx_tracing/__init__.py

These changes add python 3.7 to the tested versions and have the nox session build an sdist to install from over pip installing from the directory with an increasing .nox directory to comb through: https://github.com/pypa/pip/issues/2195.  Tox allowed us to copy sources to the venv before local installations but nox is without that functionality.  This is workaround also provides some build sanity in the process.

Include 3.7 in testing and improve nox performance

---

requirements-inst.txt
scripts/bootstrap.py
signalfx_tracing/libraries/psycopg2_/instrument.py
signalfx_tracing/utils.py
tests/integration/psycopg2_/test_instrumented_connection.py
tests/unit/libraries/psycopg2_/test_psycopg2.py
tests/unit/test_utils.py

These changes adopt dbapi-opentracing's new Psycopg connection_factory functionality: https://github.com/opentracing-contrib/python-dbapi/pull/2.  This ensures that auto-instrumented connection instances are compatible w/ the psycopg2 C extensions overall.
Also silences ImportErrors from `get_module`, which is useful for not failing on instrument() calls without proper instrumentation libs.

Update Psycopg instrumentor

---

scripts/site_/sitecustomize.py
tests/integration/lib/runner_target_script.py
tests/integration/test_runner.py

In cases where there is no preexisting sitecustomize module in python 3, sfx-py-trace will leak:
```
Failed to import the site module
...
File "frozen importlib._bootstrap", line 660, in _load_unlocked
KeyError: 'sitecustomize'
```
These changes restore our sitecustomize where no additional is provided.

Reset sitecustomize module to sfx-py-trace's

---

noxfile.py
requirements-inst.txt
requirements.txt
scripts/bootstrap.py
signalfx_tracing/libraries/psycopg2_/instrument.py
signalfx_tracing/libraries/pymysql_/instrument.py
tests/integration/psycopg2_/test_instrumented_connection.py
tests/integration/pymysql_/test_instrumented_connection.py
tests/unit/libraries/psycopg2_/test_psycopg2.py
tests/unit/libraries/pymysql_/test_pymysql.py

Also updates dbapi version to pull in `span.kind` addition and expands compatibility testing.

Add db.instance tag to pymysql and psycopg2

---

.circleci/config.yml

Adds sanity lint, unit, and jaeger bootstrap tests for each build, with added jaeger package extras job on nightly runs.
Docker-disabling pytest flags (since circle doesn't allow arbitrary docker-in-docker images) and change-dependent integration tests to be added in subsequent PR.

Minimal CircleCI

---

README.md
noxfile.py
signalfx_tracing/instrumentation.py
signalfx_tracing/utils.py
tests/unit/test_instrument.py

These changes* add the ability to prevent specific instrumentations by setting an environment variable (`SIGNALFX_<LIBRARY>_ENABLED=false`) as opposed to the current method using filtered `instrument()` calls.  They also begin to log instrumentation application errors from the main `instrument()` helper function instead of raising them.
edit: also including a workaround to the CI failure re: Tornado 6 incompatibility.

Provide instrumentation-disabling env var

---

.circleci/config.yml
.gitignore
README.md
noxfile.py
requirements-inst.txt
requirements.txt
scripts/bootstrap.py
signalfx_tracing/libraries/tornado_/README.md
signalfx_tracing/utils.py
tests/unit/libraries/tornado_/conftest.py
tests/unit/libraries/tornado_/helpers/__init__.py
tests/unit/libraries/tornado_/helpers/_test_case.py
tests/unit/libraries/tornado_/helpers/_test_case_gen.py
tests/unit/libraries/tornado_/test_tornado.py
tests/unit/test_decorator.py

Support Tornado6
This commit adds support for Tornado 6. Only change users are expected to make is to import TornadoScopeManager from `tornado_opentracing.scope_managers` instead of `opentracing.scope_managers.tornado`.
This is required as tornado_opentracing automatically exports the correct scope manager to use depending on the version of Python and Tornado being used.

Add support for Tornado6

---

scripts/bootstrap.py

If there's an existing `sfx-jaeger-client`, the first `jaeger-client` check will initiate a bound to fail uninstallation.  Swapping orders prevents this.

Ensure jaeger uninstalled

---

noxfile.py
requirements-inst.txt
requirements-test.txt
scripts/bootstrap.py
setup.py
signalfx_tracing/__init__.py
signalfx_tracing/tags.py
signalfx_tracing/utils.py
signalfx_tracing/version.py

Requires signalfx/jaeger-client-python v3.13.1b0.dev3
(https://github.com/signalfx/jaeger-client-python/pull/3)

Record signalfx version and library tags on local root spans

---

README.md
requirements-inst.txt
requirements-test.txt
scripts/bootstrap.py
signalfx_tracing/utils.py

- Tracer now always enables logging.
- Logging level is set to DEBUG when SIGNALFX_TRACING_DEBUG is set to
True.
- If SIGNALFX_LOGS_INJECTION is also set to True, the default logging
format is set automatically as well.

Updated how logging is handled

---

README.md

In some cases, running the bootstrap command is not straightforward so adding documentation on how users can install instrumentations manually.

Documented how to install instrumentation packages manually

---

scripts/README.md
scripts/bootstrap.py

Bootstrap command can now optionally print deps
Updated bootstrap command to allow users to optionally print deps
instead of installing them.
This add a new flag `-r` or `--requirements` to the bootstrap command.
When set, it forces the command to print the list of dependencies it
would've otherwise installed to console instead of actually installing
them.
This is useful for environments where the bootstrap command can't be
executed easily for example AWS Lambda.

Bootstrap command can now optionally print deps instead of installing

---

README.md
signalfx_tracing/constants.py
signalfx_tracing/utils.py

SIGNALFX_RECORDED_VALUE_MAX_LENGTH env var allows to set the max size of
attribute values. Any values larger than specified size will be
truncated. Defaults to 1200.

Add support for SIGNALFX_RECORDED_VALUE_MAX_LENGTH

---

README.md

this PR:
- fixes a little markup issue that prevented the config table from generating properly
- updates the notes for the max value length setting

fix config table in readme

---

signalfx_tracing/libraries/falcon_/middleware.py

This is a quick fix to prevent instrumentation from crashing on Falcon
<2.0. This will be followed up with another PR to either move the falcon
isntrumentation out into it's own package or prevent it from
instrumenting unsupported versions.

Falcon prevent crash on older versions

---

signalfx_tracing/instrumentation.py

Log warning instead of printing out the entire stack trace in case we
cannot import an instrumentation package. Printing out the whole stack
trace in this case causes confusion and makes users think that the tracer
crashed.

Log warning when an instrumentation package is not found.

---

README.md
noxfile.py
signalfx_tracing/constants.py
signalfx_tracing/libraries/logging_/instrument.py
signalfx_tracing/tags.py
signalfx_tracing/utils.py
tests/unit/libraries/logging_/test_logging.py

This PR adds a new env var `SIGNALFX_SERVICE_ENVIRONMENT` (or config option `service_environment`, default: `unknown`). Spans now have the environment in the `Process` field tags (so once per span batch).
If log injection is enabled, the log records have new variables available:
* `sfxService` - corresponds to the service name option's value
* `sfxService` - value of service environment option
The default logging format was changed to include these variables. For backwards compatibility  I did not remove the `signalfx.` prefix from log variables, although I guess a better option would be `[signalfx trace_id=... span_id=... service=xyz environment=foo]`
Miscellaneous:
- Fix logging tests (they were failing previously)
- Add logging tests to nox

Inject service name and environment to logs
